name: app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  animated_toggle_switch: ^0.8.3

  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.4
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  dio: ^5.7.0

  firebase_analytics: ^11.3.2
  firebase_app_check: ^0.3.1+2
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.2
  firebase_messaging: ^15.1.2
  firebase_storage: ^12.3.1

  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  layout: ^1.0.5
  package_info_plus: ^8.0.2
  sentry_flutter: ^8.9.0
  share_plus: ^10.0.2
  url_launcher: ^6.3.0
  uuid: ^4.5.1
  http: ^1.2.2
  logging: ^1.3.0
  path_provider: ^2.1.5
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

  freezed: ^2.5.7
  json_serializable: ^6.8.0
  swagger_dart_code_generator: ^3.0.0
  sentry_dart_plugin: ^2.1.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
